### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by yoavnash** [franzinc/docker-agraph#6]
I configured AllegroGraph using docker-compose and I constantly get this error upping connecting to the backend using `agraph-python`, even though the credentials seem to be correct:
`franz.miniclient.request.RequestError: Server returned 401: Invalid username/password combination.`

When I comment out the `volumes` section, then everything works fine.

From my docker-compose file:
```yml
agraph:
    image: franzinc/agraph
    volumes: # When this section is commented out, the everything works fine
      - agraph-data:/agraph/data
      - ${CERT_BUNDLE_PATH}:/etc/ssl/certs/bundle.pem
      - ./agraph.cfg:/agraph/etc/agraph.cfg
    ports:
      - "10000-10035:10000-10035"
    networks:
      - intranet
    environment:
      - AGRAPH_SUPER_USER
      - AGRAPH_SUPER_PASSWORD
    restart: on-failure
    shm_size: 4g
```

Content of file `agraph.cfg`:
```yml
RunAs agraph
SessionPorts 10000-10034
Port 10035
SSLPort 10036 
SettingsDirectory /agraph/data/settings
LogDir /agraph/data
PidFile /agraph/data/agraph.pid
InstanceTimeout 604800
SSLCertificate /etc/ssl/certs/bundle.pem 
<RootCatalog> 
 Main /agraph/data/rootcatalog
</RootCatalog>

<SystemCatalog>
 Main /agraph/data/systemcatalog
 InstanceTimeout 10
</SystemCatalog>
```
